# Generated by Django 4.2 on 2023-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='foto',
        ),
        migrations.AddField(
            model_name='topic',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_topicos/'),
        ),
    ]
