# Generated by Django 4.2 on 2023-05-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizador',
            old_name='data_nascimento',
            new_name='date',
        ),
    ]
